Success message with error toast
wazuh/wazuh-splunk pull request #1046
Opened 2021-04-06 16:44 UTC by sortizowlh

Hi team!
This PR removes invalid comparison with request data
Solves #1041

2021-04-06 16:46 UTC, Desvelao commented on SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
> +        console.error(error);
Remove the console.log

2021-04-06 20:13 UTC, frankeros requested changes

2021-04-06 20:13 UTC, frankeros commented on SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
> +          // !result.data.data ||
remove comment line

2021-04-07 07:50 UTC, sortizowlh commented on SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
> +          // !result.data.data ||
Comment removed!

2021-04-07 12:34 UTC, sortizowlh commented on SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
> +        console.error(error);
Log removed!

2021-04-07 20:36 UTC, eze9252 commented
I tested and it works

2021-04-07 20:36 UTC, eze9252 approved these changes

2021-04-08 13:40 UTC, merged