fix gear icon in fim table
wazuh/wazuh-splunk pull request #1077
Opened 2021-04-28 15:14 UTC by eze9252

Hi team, this resolve:

- fix position gear icon im fim table

2021-04-29 18:35 UTC, Machi3mfl commented
Fixed in small resolutions.

<img width="1026" alt="Screen Shot 2021-04-29 at 15 32 35" src="https://user-images.githubusercontent.com/6089438/116601059-6684b780-a900-11eb-9375-6210ae92b47a.png">

2021-04-29 20:04 UTC, frankeros requested changes

2021-04-29 21:11 UTC, Machi3mfl commented on SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
> +                <wazuh-table id="agents-fim-table" custom-columns="true" flex path="'/syscheck/' + agent.id" row-sizes="[12,10,8]"
Fixed, changed id property for class property.

2021-04-30 19:31 UTC, Desvelao commented
Tested ✅ 

Good job! 

![image](https://user-images.githubusercontent.com/34042064/116745476-6cab8e80-a9fb-11eb-8c06-50290c3b2d79.png)

2021-04-30 19:32 UTC, Desvelao approved these changes
LGTM!

2021-04-30 21:00 UTC, frankeros approved these changes
LGTM!

2021-04-30 21:02 UTC, merged