Added cache control
wazuh/wazuh-splunk pull request #1078
Opened 2021-04-29 17:06 UTC by Machi3mfl

Hi Team, this PR add
- Show a warning toast after app loaded if the app version of browser and backend are differents. The message toast advices to the user that need to clear browser cache.
- Added a `prebuild` script that refresh the version and revision number.

Closes #1072

2021-04-29 17:14 UTC, Machi3mfl commented
<img width="1440" alt="Screen Shot 2021-04-28 at 17 57 40" src="https://user-images.githubusercontent.com/6089438/116591327-0e948380-a8f5-11eb-950d-fbc4987e624e.png">

2021-05-03 10:56 UTC, CPAlejandro requested changes

2021-05-03 10:56 UTC, CPAlejandro commented on SplunkAppForWazuh/appserver/static/js/services/app-version/appVersionService.js
> -            let appInfo = info;
Would it be missing here to declare the appInfo variable?

2021-05-03 16:07 UTC, Machi3mfl reviewed
Comments revolved

2021-05-05 14:40 UTC, frankeros commented
The script is changing the const name 
![image](https://user-images.githubusercontent.com/26828184/117159384-9b788a80-ad96-11eb-8049-460d33a857d1.png)
I'm fixing this now

2021-05-05 14:58 UTC, pablomarga approved these changes
LGTM!

2021-05-05 16:40 UTC, merged