Feat/crud role mapping
wazuh/wazuh-splunk pull request #1169
Opened 2021-11-03 17:37 UTC by eze9252

Hi team,
This PR added new CRUD of Roles Mapping on the security section.
Closes #1153 

List Role Mapping: 

![Captura de pantalla de 2021-11-03 18-41-04](https://user-images.githubusercontent.com/36004787/140165557-f27f59a4-4ba1-41be-bf9f-c27cba169a3e.png)

Create Role Mapping:
![Captura de pantalla de 2021-11-03 18-54-02](https://user-images.githubusercontent.com/36004787/140165642-5e891b4e-7ef7-4889-889c-73b18f128c36.png)

See and update Role Mapping:
![Captura de pantalla de 2021-11-03 18-41-14](https://user-images.githubusercontent.com/36004787/140165806-df73e969-640d-4256-959e-393326529354.png)

Delete Role Mapping:
![Captura de pantalla de 2021-11-03 18-54-11](https://user-images.githubusercontent.com/36004787/140165867-7ad16035-7d9e-4d71-af8e-a1e6ecbdabd6.png)

2021-11-04 12:29 UTC, gabiwassan requested changes
Just some simple comments, and please check to apply `prettier` for the style code.

2021-11-04 12:29 UTC, gabiwassan commented on SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
> +            <td ng-if="isLookingGroup() " ng-click="$event.stopPropagation()"
I think this method `isLookingGroup()` is for Agents Groups

2021-11-04 12:29 UTC, gabiwassan commented on SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
> +                    this group</span>
This message is referred to groups not to Role Mapping 🤓

2021-11-08 09:04 UTC, Desvelao commented
**review**:

Testing:
- Table
  - List role mapping ✅ 
  **suggestion**: use `Roles` instead of `roles` for the column. Is there some limitation to do this?
  **suggestion**: use the role name instead of its ID in the role mapping table
  **suggestion**: the last column should be named `Actions`. See another security tabs.
  ![image](https://user-images.githubusercontent.com/34042064/140707996-c1d77574-aab8-4b73-b3f0-281e366243fa.png)
  - Manage columns visibility ✅ 
  - `action:edit` (open the editing view) ✅ 
  - `action:delete` ❌ 
    - Cancel ✅ 
    - Confirm ❌ 
    **issue**: The role mapping rule is deleted but there is an error when trying to list again and update the table 
- Add new role mapping
**question**: Should we add the rule JSON editor?
  - Role multi-select ✅
  - User multi-select ✅
  - `action:save` :x:
  **issue**: If I try to edit the role mapping an error is thrown and the save button keeps processing indefinitely: 
  ![image](https://user-images.githubusercontent.com/34042064/140709960-761a432f-dd05-4092-a4c1-6e87af9565b3.png)
Request:
 ``` 
<SPLUNK_HOST>:<SPLUNK_PORT><SPLUNK_BASE>/api/request
```
![image](https://user-images.githubusercontent.com/34042064/140710545-372aad60-c580-4068-b447-66aaa233cd12.png)

Response:
```json
{"error": "'error'"}
```

2021-11-11 12:09 UTC, merged