Update get `/agents/summary/status` response
wazuh/wazuh-splunk pull request #1355
Opened 2022-07-12 11:06 UTC by yenienserrano

**Description:**

Added agent synchronization status in the agent view.
And the endpoint response type has been modified `GET /agents/summary/status` so the responses of the views using that endpoint have been fixed.

**Issue:**

- #1309

**Test:**

1. Navigate to the following views:
         - Overview
         - Management/Status 
         - Agents
2. The number of agents in the different states should be displayed. 
3. in the agent module in the details part there should appear Agents synced and in the table there should be a Synchronized column.

Screenshot:

Overview:

![image](https://user-images.githubusercontent.com/63758389/178476021-2286ae4b-aeea-4108-b416-66db02238496.png)

Management/Status:

![image](https://user-images.githubusercontent.com/63758389/178476118-1c07cd07-23ae-4366-9d05-58a9e6b73a65.png)

Agents:

![image](https://user-images.githubusercontent.com/63758389/178476182-60f4add1-ef48-482c-907d-b1a508208af4.png)

2022-07-13 10:10 UTC, asteriscos approved these changes
CR: Use constants for variables that are not reassigned.
Test: :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/9343732/178709233-db55129e-5e35-44f0-8f3a-877e4e0b4487.png)

2022-07-13 10:10 UTC, asteriscos commented on SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
> +        let summary = this.formatAgentStatusData(parsedResult.agent_status.connection)
Many of these variables are not reassigned and therefore can be constants.

2022-07-14 14:25 UTC, chantal-kelm approved these changes
CR: :heavy_check_mark:
Test: :heavy_check_mark: 

![Screenshot from 2022-07-14 11-23-36](https://user-images.githubusercontent.com/99441266/179005733-0286c70b-4d61-41fb-ad9f-2c4b1a715a6d.png)
![Screenshot from 2022-07-14 11-23-53](https://user-images.githubusercontent.com/99441266/179005739-8c6b205f-9d48-46ae-bf6c-66484cc624ab.png)
![Screenshot from 2022-07-14 11-24-06](https://user-images.githubusercontent.com/99441266/179005740-df54d7a6-668b-4550-a761-3192535bf597.png)

2022-07-20 14:23 UTC, AlexRuiz7 commented on CHANGELOG.md
> +- endpoint `/agents/summary/status` response was adapted. [#1355](https://github.com/wazuh/wazuh-splunk/pull/1355)
Change to: 
> Update response handlers for the endpoint `/agents/summary/status`

2022-07-20 14:24 UTC, AlexRuiz7 commented on CHANGELOG.md
> +## Wazuh v4.4.0 - Splunk Enterprise v8.1.4, v8.2.2, v8.2.4 - Revision 4401
Splunk Enterprise v8.1.[1-10], v8.2.x

2022-07-20 14:26 UTC, AlexRuiz7 requested changes

2022-07-20 14:26 UTC, AlexRuiz7 commented on SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
> +                  <p>Agents synced</p>
Change to "Synced agents", as done in [Kibana](https://github.com/wazuh/wazuh-kibana-app/pull/3874/files#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462R226)

2022-09-07 11:54 UTC, AlexRuiz7 approved these changes
- Code review: ✔️
- Test: ✔️

2022-09-07 11:55 UTC, merged